### ISSUE TITLE
[BUG] Hitting a snag when trying to install a module

### ISSUE THREAD

**Issue by zgfg** [Androidacy/MagiskModuleManager#2]
Just installed the new AA MMM v2.0.2, and I have again the same bug as previously reported for Fox MMM v2.0.1 (it was fixed in one of the Action builds and I successfully tested):
https://github.com/Fox2Code/FoxMagiskModuleManager/issues/309

But now again, when I try to install any module from the online Repo (Alt Repo), I get "Hitting a snag" and the installation of the module fails

Tried also with an Upgradable module, the same

Same bug also when I downloaded a module and tried to install the module zip file from the local storage (Download folder)
![Screenshot_2023-05-03-11-01-32-124_com fox2code mmm](https://user-images.githubusercontent.com/51943147/235881049-9526104a-9ba0-4226-9a51-fbf9e46cb0f6.jpg)

**Comment by mrkylegp** [comment]
I have the same problem. Redmagic 8 Pro, android 13.

Can't use v2.0.2. V1 works fine.

**Comment by zgfg** [comment]
> We are tracking this internally and via Sentry and will update when we can reproduce.

You can't reproduce?
Try to install any module from the repo or from your local storage

**Comment by mrkylegp** [comment]
> This bug only seems to be effecting 0.01-0.1% of users making it rather hard to reproduce

That seems odd. What would the variance be in Android 13 that would only affect such a small number of users I wonder.

**Comment by zgfg** [comment]
I can reproduce any time with my both phones, Android 11 and Android 12

The same bug was introduced in v2.0.1 and you fixed it in the Action build>
https://github.com/Fox2Code/FoxMagiskModuleManager/actions/runs/4826124597

So please compare what got wrong in the later changes before releasing v2.0.2

**Comment by badassaccount** [comment]
I also encounter this bug both local storage and Online install. My Device was Poco MIUI 13 

Stacktrace:
java.lang.ExceptionInInitializerError
	at hj2.a(SourceFile:10)
	at hj2.g(SourceFile:1)
	at hj2.i(SourceFile:223)
	at hj2.setTime(SourceFile:34)
	at xj2.k(SourceFile:532)
	at xj2.<init>(SourceFile:105)
	at p70.c(SourceFile:73)
	at com.fox2code.mmm.installer.InstallerActivity.L(SourceFile:234)
	at lm0.run(Unknown Source:14)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalArgumentException: class je is not a concrete class
	at m60.c(SourceFile:59)
	at m60.<clinit>(SourceFile:10)
	... 10 more

I hope it will fix soon, kodos to developers.

**Comment by raulvasquez** [comment]
Same problem here as well.

**Comment by Nek-12** [comment]
Lol what can't you reproduce here? You literally used WebView from multiple processes

**Comment by zgfg** [comment]
> To address the real issue here we are **completely aware** of what the error says, but as we've mitigated that error for ages and the crash occurs for less than 1% of users and on none of our test devices or emulators we're having a hard time coming up with solutions.

Saying again, see above, compare against one of the Action builds between v2 0 1 and v2.0.2 where it worked (already for the v2 code base)

**Comment by Avsynthe** [comment]
Experiencing the same issue on an Asus ROG Phone II running A11. I thought it might be a shamiko issue at first as that's the only upgrade I have. Can confirm it doesn't matter if I attempt from repo or storage.

I've had two different errors appear for me though, though after resetting the app I received the one listed here and it's stayed that way. If I can reproduce the first error I'll post here.

**Comment by LeeBinder** [comment]
Debug apks from Actions in which this bug is fixed (at least for me on my phone with LOS 17.1/ Android 10): https://github.com/Androidacy/MagiskModuleManager/actions/runs/4898981912#artifacts

Kudos to you, @androidacy-user , for the quick fix 👍 🥇

**Comment by zgfg** [comment]
I have just tested Action build:
https://github.com/Androidacy/MagiskModuleManager/actions/runs/4898981912

and it works - thanks

- updated module from Repo
- updated module by JSON (module N/A on Repo)
- installed module from local storafe

**Comment by iamMG** [comment]
Yeah, I too am facing this issue. Reinstalling either v2.1.1 or v2.1.0 doesn't fix it.

**Comment by Albirew** [comment]
nevermind, they updated their apk, but only [outside github](https://www.androidacy.com/downloads/?view=FoxMMM) (witch is somehow concerning since they can just edit release and replace apk file)

**Comment by LeeBinder** [comment]
@Albirew 100% agreed. I've recommended that exact same thing before, [here](https://github.com/Androidacy/MagiskModuleManager/issues/33#issuecomment-1589178610). But such remarks aren't considered helpful and rational but much rather spam, see [the reply](https://github.com/Androidacy/MagiskModuleManager/issues/33#issuecomment-1589737715) a few post later in that same (and since then locked) topic ..

**Comment by iamMG** [comment]
> nevermind, they updated their apk, but only [outside github](https://www.androidacy.com/downloads/?view=FoxMMM) (witch is somehow concerning since they can just edit release and replace apk file)

I tried apk from there. Still 'hitting a snag '.

**Comment by LeeBinder** [comment]
@iamMG it's a DIFFERENT app, adding a 2nd FoxMM icon into your launcher's app list! You need to remove the old non-functional one here from GitHub so that you can ONLY launch the app from their website via its icon!

**Comment by LeeBinder** [comment]
@androidacy-user one icon for the GitHub "debug" build, + one (another) icon for the build from your website which even has a different signature (labeled "signed") = TWO icons, for sure. You can test it yourself :)

**Comment by LeeBinder** [comment]
@androidacy-user :

- on https://www.androidacy.com/downloads/?view=FoxMMM there are only release builds
- on https://github.com/Androidacy/MagiskModuleManager/releases/tag/v2.1.1 there also are only release builds

No "debug" builds to be seen..

PLEASE for heaven's sake, DO test yourself. What you're writing simply is NOT reflected by reality!!

**Comment by Albirew** [comment]
> No "debug" builds to be seen..

Debug builds are on [github actions](https://github.com/Androidacy/MagiskModuleManager/actions) page (see green check items subtitled with "Generate APK Debug", then scroll on artifacts), not on release page

**Comment by scrattatattat** [comment]
Still not working in September 23, and ongoing since May, bit ridiculous if you ask me. What are you guys actually doing over there? All you have to do is maintain stuff, we are the ones that do the real work and development, and you charge us for it. For what? Cant even access our own published works
